[package]
name = "pngifier"
version = "1.0.0"
authors = ["Wilson Nguyen <wilsonqnguyen@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flate2 = { version = "1.0", features = ["cloudflare_zlib"], default-features = false }
clap = "2.33.1"
crc32fast = "1.2.0"
lazy_static = "1.4.0"
winapi = "0.3.9"
